# Generated by Django 3.0.7 on 2020-06-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm', models.DateTimeField(auto_now=True, verbose_name='Дата события')),
                ('temperature', models.PositiveIntegerField(verbose_name='Температура')),
            ],
        ),
    ]
