# Generated by Django 3.0.7 on 2020-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='carbon_dioxide',
            field=models.PositiveIntegerField(default=0, verbose_name='Углекислый газ'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='temperature',
            field=models.PositiveIntegerField(default=0, verbose_name='Температура'),
        ),
    ]
